### ISSUE TITLE
Max key fee message swallowed by Error modal

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1025]
## The Issue
If a higher has a max key fee configured in settings and try to download/stream something with a higher fee, the app attempts a get call which then fails due to the key fee.  The user is presented with:
![geterror](https://user-images.githubusercontent.com/8120721/36329574-70ce1d4a-1334-11e8-906e-0f0bd3c9ccfb.png)
which doesn't tell them the reason for the download failure. 

The daemon returns: `2018-02-16 15:27:23,421 ERROR    lbrynet.daemon.Daemon:703: Failed to get howl (Key fee 12.9729156459 above max allowed 10)`

Options:
1) App should check the max key fee setting even before allowing the user to purchase/attempt to download it and prompt the user accordingly. 

2) The pop-up screen should pass the error message from the daemon to the user.

### Steps to reproduce
1. Configure a key fee of 10LBC setting in the Settings screen
2. Try to download lbry://itsadisaster / lbry://howl

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@tzarebczan is there a ticket for adding error codes to lbry? I thought there was but could not find.

Error codes would allow this to be handled in a much cleaner way (like directing them to settings rather than just showing the error).

@jackrobison @eukreign I'm guessing you're already convinced of the necessity of codes, but in case you want some real world encouragement for their addition here it is.

**Comment by tzarebczan** [comment]
I'll check on the error code ticket and open one if needed.

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry-desktop/issues/2194
