### ISSUE TITLE
Subscribing to channel shows unexpected notification

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-desktop#1341]
## The Issue

I clicked `Subscribe` on the Cop Chronicles channel, and got a notification that made no sense (see top-right corner of screenshot).

### Steps to Reproduce
1. go to `@copchronicles` channel
2. click Subscribe
3.

### Expected Behaviour
Just the normal "Subscriptions 101" popup.

### Actual Behaviour
I got that, but I also got an extra OS notification.

## System Configuration

{"lbrynet_version": "0.19.1", "platform": "Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "python_version": "2.7.12", "os_release": "4.4.0-116-generic", "lbryum_version": "3.2.0", "lbryschema_version": "0.0.15", "processor": "x86_64", "build": "release"}

## Screenshots

![screenshot at 2018-04-17 21 24 09](https://user-images.githubusercontent.com/362784/38906721-42f54804-4286-11e8-8127-bd6d66013d4a.png)

**Comment by tzarebczan** [comment]
Thanks @lyoshenka! Another feature of auto subscribe is that the last free content is downloaded automatically (this was not mentioned in the pop up as the consensus was not to). 

@liamcardenas is this something you are working on in your subscriptions changes? In this case it's really unexpected because the item is paid content, something that shouldn't be downloaded.

Would we expect this notification on free items when subbing to a channel? What if the content was already downloaded?

**Comment by tzarebczan** [comment]
We no longer automatically download the latest content for newly subscribed channels, so this notification is not generated. Closing...
