### ISSUE TITLE
Regtest and Protocol Development Support

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry-desktop#1526]
It would be very helpful to the protocol team if we could use the app when developing the daemon and other components. This is currently not possible because the app requires specific versions of daemon and does not understand regtest addresses.

I've made a new branch of the app with offending code commented out, this should provide some guidance on what areas of the app need to be updated to support daemon development and the regtest network:

https://github.com/lbryio/lbry-app/compare/regtest_dev_hacks

**Comment by tzarebczan** [comment]
@seanyesmunt will review and I can try to include in my patch release if the code is simple enough to cherrypick. I think we'd need some type of way to tell the app to bypass these checks for regtestmode - not sure what the easiest way of doing that.  It's one thing to disregard the daemon version but the daemon running changes would be in a different boat.

**Comment by kauffj** [comment]
This is two changes:

- Relax the daemon version check, especially outside of production
- Turn the definition of a valid address into an environment setting or something provided by the running daemon instance.

It is reasonable to expect engineers interested in running the app against test net to have to make configuration changes.

**Comment by tzarebczan** [comment]
I asked Lex about the daemon shutdown removal, his response:
Two reasons: 1. During development I don't want the app to shutdown when something goes wrong, I want to keep it running so that I can diagnose. 2. Whenever the app experiences an issue it tries to start its own daemon.

@seanyesmunt we could do enable this mode based on an environmental variable, right?

@eukreign I won't be able to get this into my patch release, so we'll have to get it scheduled for the next sprint. We are deep in redesign mode at the moment.

**Comment by eukreign** [comment]
Okay, thanks for looking into this. I can keep using my hacks branch. I actually just got @kafene setup with it yesterday as well.

**Comment by tzarebczan** [comment]
@seanyesmunt re-opening to address Jeremy's comment about showing the protocol warning but allowing the user to continue.
