### ISSUE TITLE
Can't watch my own pay streams

### ISSUE THREAD

**Issue by 42degrees** [lbryio/lbry-desktop#1723]
I've been playing around with setting my items to require payment to test my publishing app, but then I noticed that LBRY was going to require that I pay the vig for watching my own videos.  It seems like there should be a way to watch your own streams without having to pay yourself (and lose LBC due to transaction fees).

**Comment by tzarebczan** [comment]
Thanks for opening this issue! This would most likely depend on https://github.com/lbryio/lbry/issues/803 unless we do some type of workaround using claim_list_mine to check ownership of a claim. 

This situation will only occur if you delete the file after you publish it, otherwise, you should be able to play it after publishing since file_list will know that you published it.

**Comment by tzarebczan** [comment]
This should be fixed in an upcoming SDK release.
