### ISSUE TITLE
Suggested channels after subscribing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2180]
## The Issue
Cool feature I noticed on YouTube recently where they show you a list of similar channels after subscribing to one. We could do this in a similar way to related content along with Search, but I think we'll need creator profiles before we can do this well. Right now we'd only be able to search on name, which won't give good results. 

![image 2](https://user-images.githubusercontent.com/8120721/51076657-3fd7df80-1669-11e9-9e20-a87ddf94cc87.png)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by ITwrx** [comment]
I just went to my subscriptions page (i have two sub'd channels) and instead of my subscribed channels being shown, i am shown other channels i am not subscribed to. This made me furious with molten rage! :) It was as if the fat mouse was mocking me...

I can see how this feature might be useful one day, but IMHO in needs to be a little more discrete and a user shouldn't have to click to show their subscribed channels. Subscribed channels should be shown first and then suggested channels, clearly delineated so as to not appear coercive/pushy.
thanks

**Comment by tzarebczan** [comment]
This is only shown a single time or after clearing app cache. Otherwise, it will show you your synced content. We do show suggestions in the latest only section if all your current channels don't have any new content.

**Comment by ITwrx** [comment]
oh, ok. thanks
