### ISSUE TITLE
Show play counts

### ISSUE THREAD

**Issue by skhameneh** [lbryio/lbry-desktop#2376]
I'd like to see total play counts as well as the current "views" (which are actually download count) on content I publish.

**Comment by tzarebczan** [comment]
Discussed wth @skhameneh - the intention is to show total views as opposed to downloads. Right now we only count a content view when you download it. 

My only concern is that showing multiple counts to users would be confusing, especially since we can't guarantee which are uniques or not (I can just delete the content, and it counts as a view again).
