### ISSUE TITLE
Comments version 1

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#2518]
- Flat CommentList with dates and authors by channelName
 - "Enable Comments" button shows modal explaining, then shows CommentCreate panel.
 - CommentCreate component allows typing text, choosing / creating channel identity.

 - Handles case of comment server being down?

**Comment by seanyesmunt** [comment]
Do we need a modal explaining this? Can it just be above the comment box and removed when you click it?

**Comment by jessopb** [comment]
@kauffj ?

> Do we need a modal explaining this? Can it just be above the comment box and removed when you click it?

**Comment by jessopb** [comment]
Partially blocked by sdk comment pr and sdk 0.38

**Comment by seanyesmunt** [comment]
I would prefer something like this. Then we don't even need an "Enable Comments" button.

<img width="600" alt="Screen Shot 2019-05-29 at 4 55 28 PM" src="https://user-images.githubusercontent.com/16882830/58590708-aa617480-8232-11e9-8349-774a02f1da93.png">

**Comment by kauffj** [comment]
Just code a modal or some place where we can put 1-2 paragraphs of introductory text that has to be acknowledged before first comment submit and I will fill it in on review.

**Comment by seanyesmunt** [comment]
What (generally) has to be acknowledged?

**Comment by osilkin98** [comment]
> What (generally) has to be acknowledged?

That comments are finally a feature. That way instead of clicking on it to get that `Thanks for your Support` message, it just opens up the comment creator menu. It'd be kinda cool to have confetti pop in from the sides when they open it. 

> "Enable Comments" button shows modal explaining, then shows CommentCreate panel.

This but something that gets people more pumped up like `Ready to Comment?`, or `Comments are Finally here, ready to have a try?`


Anything beyond that, we shouldn't include. Since the comment server is an [official in-house project](https://github.com/lbryio/comment-server), there doesn't make much sense to talk about it not being "official." 

As for saying they're not on the Blockchain, they should work the same anyway so that distinction really shouldn't matter to the end user. When the real thing comes in, we can impose whatever changes we need. For now, we should just let people enjoy it.
