### ISSUE TITLE
Replace i18n call with one that supports interpolation

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2555]
@kauffj commented on [Tue Jun 18 2019](https://github.com/lbryio/lbry/issues/2245)

Evidently the `__` call being used by the app does not all interpolation of values.

It should support strings that work or look something like this:

```
__('You have %amount% credits', { amount: 5 })
```

**Comment by kauffj** [comment]
@tzarebczan asked me the right format to use for this.

Technically the `gettext` standard does not support named interpolation of parameters, only the parameters taken by good ol' `sprintf` (i.e. the standard says do __('Your files are stored in the %s directory', directoryName) ).

However, pretty much every language supports named parameters in their implementations, and I think it is worth doing so. The common formats are `%label%, `%(label)`, and `%{label}%. I see this as all basically equivalent, so if someone sees a problem with one of these, please speak up.

Once the format is decided, it's pretty simple to modify the `__` method (which I think does basically nothing right now). Off the top of my head, I think it can be done in one line:

```
(message, args) => Object.keys(args).reduce((arg, interpolatedMessage) => interpolatedMessage.replace('%' + arg + '%', args[arg]))
```

We may ultimately want to bring in a library, because proper `gettext` does a lot more than above. But if the goal is to just reach the next step (basic interpolation) without determining anything more, the above will get the job done.

I think the biggest challenge, and one that should be thought about before picking a library, is how we'll handle interpolation when we want to mix HTML in a string (e.g. you want to construct something like `<div>Some text <span>interpolated value</span> some text</div>`).

It is worth examining what other React projects do to handle the above case.

**Comment by kauffj** [comment]
I'm dumb. We're already using `y18n` (https://github.com/yargs/y18n)

It does not appear to support named parameters, just the `gettext` `sprintf` style.

**Comment by jsigwart** [comment]
This appears like it may be affecting some of the Polish translations as some won't translate.

**Comment by kauffj** [comment]
https://github.com/formatjs/react-intl
