### ISSUE TITLE
store claim search results (claims + channels) in redux state

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2632]
## The Issue
Right now we only store resolve + local claim list calls to redux state. We should consider storing results from claim search in redux state as well. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
IMO this should be avoided for as long as we can deliver reasonable experience without it (it complicates design and it either hinders UX or uses short timings which diminish value). It probably makes more sense to cache on the wallet server which has the potential to know when a cache should be invalidated. If caching on the wallet server, we ought to be able to get extremely good performance at low resource cost.

Are there any specific reasons you want to add this?

**Comment by seanyesmunt** [comment]
I'm going to close this since it's already done.

Caching is absolutely necessary for a really good scroll restoration experience. Even if the api request is extremely fast, there are still a number of edge cases that add a lot of complexity to the claim list component. Then even if we are handling the restoration perfect, there still can be jumpiness from from the brief time that we are re-fetching the claims. 

It seems to work pretty well to use the cached results when navigating backwards, but always re-fetching results when navigating forward. This still has some edge cases, but works pretty well.
