### ISSUE TITLE
Pop out player improvements / feedback

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2750]
- [ ] make it clearer on how to drag around

- [ ] don't pop out if video is completed/errorred/paused

- [x] don't pop out on image files (@kauffj edited to make this an assertion)

- [ ] better support for small screens (appears off screen)

- [ ] don't pop out on edit? - this causes this bug: https://images-ext-2.discordapp.net/external/jUMk0-Vq1LFuqhJGhMnzqCJuuD6zu2aOG49ualhw5h4/https/i.gyazo.com/9c5260df40d328b0adc7eefd3883df9c.mp4

- [ ] don't pop out if clicking back? 

- [ ] turn off autoplay? A couple users have complained about it. 
- [ ] pops out off screen.

**Comment by jessopb** [comment]
If I go to a video page and click edit, it opens the PIP.
If I do the same on an image page, it doesn't.
Until I edit the file and change it to a video. Then the filerenderfloating ( i assume ) pops into existence because it was there all along just not showing because it was an image.

One solution is to not autoplay on file page if isMine

**Comment by seanyesmunt** [comment]
We should `setPlayingUri(null)` when you click the edit button
