### ISSUE TITLE
Auto-detect OS user language

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#2955]
**Is your feature request related to a problem? Please describe.**
Need manualy find and implement other Languages.

**Describe the solution you'd like**
App should pull informations from OS about user language, and try set translation automatic, or prompt user if he want use his native language or stay in English. If Transfix return no translation for that language it should set it to default English.

**Comment by tzarebczan** [comment]
Great suggestion!

**Comment by kodxana** [comment]
Suggestion how to get is locale https://github.com/sindresorhus/os-locale

**Comment by peterjgrainger** [comment]
Can I have a go at this one?

**Comment by tzarebczan** [comment]
@peterjgrainger welcome to LBRY! Sure, take a stab at it!

**Comment by kauffj** [comment]
@peterjgrainger FYI language is being accessed before UI loads on both web (where this is probably necessary) and desktop (where it's probably not necessary but was more efficient from development perspective).

You can see this in `index-web.html` and `index-electron.html`. If you have any questions, don't hesitate to tag me!

**Comment by Rupeshiya** [comment]
@kauffj Can I work on this?
I think simply can be done using https://github.com/sindresorhus/os-locale.

**Comment by peterjgrainger** [comment]
@kauffj thanks for the offer of help will probably need it!

Just getting the project set up now

**Comment by peterjgrainger** [comment]
@kauffj my thought is to use the `app.getLocale()` builtin function in electron https://github.com/electron/electron/blob/master/docs/api/app.md#appgetlocale

would the best place to put that be here? https://github.com/lbryio/lbry-desktop/blob/6471aa2140708f2ca3aaa5c15513ef4d02ceacbd/src/platforms/electron/index.js#L42

Also do you think it is a good approach to default to the system OS then give the choice to change it on the "Customize Your Homepage" discover view 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/1332395/66585378-9df50d00-eb7e-11e9-894e-123f8e5a6ec7.png">

**Comment by kauffj** [comment]
@peterjgrainger yes, `app.getLocale()` is the way to go. If we want this to work on both desktop and web, then there are probably two changes to make:

1. For desktop, use `app.getLocale()` to set the language _before_ rendering `index.html`. I believe you'll need to do this in `createWindow.js` somewhere between creating the window and the call to `loadURL`.
1. For web, use [NavigatorLanguage](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language) to set the language directly in `index-web.html`. 

In both cases, if language is already set on `window.localStorage`, that value should take precedence.

Also note that our language files are currently only two letters rather than the 4 letter language + locale codes. If either `app.getLocale` or `NavigatorLanguage` return 4 letter codes, the language portion needs to be stripped off of this value.

Please also ensure your code works in the cases that the detected language is not one we support.

Thanks @peterjgrainger!

**Comment by peterjgrainger** [comment]
@kauffj Can you have a look at the PR and let me know if I am on the right track?

I'll do the web side as well. I'm pretty new to Electron and React so please let me know if I'm doing something wrong!

**Comment by jsigwart** [comment]
I was looking to file a new issue, but then saw this one. What I was going to file was a suggestion for the language selection menu to be moved from Settings and onto the Home page (an obvious place). Imagine the UX if you speak Chinese and have to try to navigate through an English interface to search for where you can select your native language - not fun. 

I wasn't sure how soon this issue would be finished, which would probably negate the need for the language selector.

**Comment by kauffj** [comment]
@jsigwart (and @peterjgrainger) this will almost certainly ship in the next release.

Julie, the other change remaining issue to tackle here is https://github.com/lbryio/lbry-desktop/issues/3186 (right now you can only change language if you sign in).
