### ISSUE TITLE
"Save Password" checked on incorrectly

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3087]
Even if you don't set the "Save Password" option on startup, the option is enabled in Settings because it's reading from the in-memory password setting. It should reflect the startup option. 

If you do delete the password, you don't see it updated until you press ctlr-R. 

Should take https://github.com/lbryio/lbry-desktop/issues/3078 into account when fixing.

**Comment by jessopb** [comment]
Settings "save password" checkbox is true due to this line:
https://github.com/lbryio/lbry-desktop/blob/508f2249ba3b2ce0c332c2901c299f39cddacd77/ui/page/settings/view.jsx#L109

which pulls a sessionpassword from utils/saved-passwords that isn't necessarily a keychain-saved password.

Needs a bit more consideration before solving.
