### ISSUE TITLE
Quick hit: limit publish form to 5 tags max

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-desktop#3721]
This will discourage people from slapping every single tag onto the things they publish and should help with mistagged content.

**Comment by tzarebczan** [comment]
As a user I'd want to know why certain content (i.e. YouTube sync) gets to apply more tags. I also dont think this will fully solve the tag abuse, but it's a good step towards trying to curb it. Part of the problem is that users just add the first tags they see on the list...

We should also:

Don't show the first few default tags? 

Make it clearer you can add your own tags if they don't show up on the list.

Auto suggest mature tag based on title / file name (i.e. porn hot XXX etc in name)

**Comment by kauffj** [comment]
Mainly repeating Tom above:

- Find way to be smarter about default tags (possibly read tags from content they've published or watched)
- Make sure mature is always shown prominently. Possibly add set of words to auto-match/apply mature.
- Always show the exact term typed as a possible tag to apply (2 character minimum)
