### ISSUE TITLE
re-enable repost setting

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#3774]
Disabling it now because we never thought about how emails work for reposted content.

**Comment by tzarebczan** [comment]
API issue: https://github.com/lbryio/internal-apis/issues/1252

**Comment by tzarebczan** [comment]
It also defaulted to false for all my logins...default should be on I think (previous behavior, we want to use it as discovery). Global setting is a good start...

Twitter actually allows turning off reports on a per channel level. We'd probably need an sdk call, or can parse out on app side (quicker, but would need to select more data, deal with more edge cases).

**Comment by tzarebczan** [comment]
Per discussion, we'll use a simple tag add/remove api call to enable/disable it. See https://github.com/lbryio/internal-apis/issues/1252 for details. By default it will be enabled, and will only not send if someone opts out in the app.

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-desktop/pull/3712

**Comment by tzarebczan** [comment]
noreposts tag has been created.

add/remove via simple api call: https://github.com/lbryio/lbry-desktop/commit/31cca0c444ee166b8d0d025f58368784ce1fef6d#diff-ad5e0b4142d08cd6b3f6229750c3f3afR41

- [ ] need to make sure reposts are enabled by default (no tag is set)
- [ ] if tag is added, setting is disabled
- [ ] need to make sure this setting is synced across all devices (otherwise the tag/setting may get out of sync). Can also read from https://api.lbry.com/tag/list?auth_token=xxxxxxxxx

**Comment by jessopb** [comment]
Why is setting disabled if tag is added? This is not clear to me.

**Comment by tzarebczan** [comment]
The default behavior will be to have reposts enabled, so all users won't have the 'no reposts' tag.  If they disable it, then the tag is set.
