### ISSUE TITLE
Translations not updating from transifex

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#3807]
New strings seem to be updating, but old strings that have been re-translated are not, including both desktop and lbry.tv. Here's an example from Serbian language:

![serbian](https://user-images.githubusercontent.com/1363664/76172310-a4011100-6151-11ea-897d-1d306808e958.png)

**Comment by kauffj** [comment]
Because the English on the left is not what is being used here. Sometimes old strings get left in the translation file even if not being used.

Check lbry.tv and you'll see the full current text is:

Multi-language support is brand new and incomplete. Switching your language may have unintended consequences, **like glossolalia**. (emphasis mine)
