### ISSUE TITLE
Determine notifications 1.0

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#3875]
1. Data design
1. Origin design (IAPI vs. client side vs. wallet server (?) )
1. Most useful/tractable notification to start with

**Comment by kauffj** [comment]
Proposal: https://docs.google.com/document/d/1hE_yWrtrFTVwMEDCp8btH4c7Q9hoM32ebLrwVwCVpNc/edit

**Comment by kauffj** [comment]
@eukreign any interest in making a case that the wallet server should compute any of these rather than IAPIs?

**Comment by eukreign** [comment]
My hunch is that a notification system is inherently centralized and so should only be available for "real logged-in users". You need to have their information on lbry servers to determine if a notification should be sent to them.

So far the scope of the SDK codebase has been to only support decentralized features.

That's not to say that some internal APIs couldn't use the SDK (especially once we add postgresql/mysql support so that it can scale better) to do wallet specific notifications for users that are plugged into the LBRY Inc ecosystem (have logins).

With SDK supporting a real relational database I can see lbry.tv and any notifications service connecting either directly to this db or via an SDK instance to get what they need.

**Comment by kauffj** [comment]
Yeah, we're going to do this in IAPIs. I think there is a model where we eventually bring some of what IAPIs does into the wallet server, at which point it would be available to users without accounts. But let's leave that for when we have more resources.
