### ISSUE TITLE
Flatpak version open another process even if it's already running

### ISSUE THREAD

**Issue by REIS0** [lbryio/lbry-desktop#3898]
**Bug**
lbry desktop loads another instance even though is already running

![image](https://user-images.githubusercontent.com/38042161/77657909-daba9200-6f6d-11ea-9a46-2b7c796ec5b1.png)

![image](https://user-images.githubusercontent.com/38042161/77658110-210ff100-6f6e-11ea-9d9e-6c1cc9d8d0dd.png)

**To Reproduce**
1. Open lbry
2. Close
3. Open lbry lauching from other source besides the system tray
4. Now there's two lbry process running

**Expected behavior**
To open the already running lbry

**System Configuration**

- LBRY Daemon version: 0.63
- LBRY App version: 0.43.4 from Flatpak
- LBRY Installation ID:  4y64Q5nBxKmo866GngPfXHkA6HDN53s5cD3bswhpfue3HtXoZk58AnJcs1fLDnqgPi
- Operating system: Pop_OS! 19.10

**Comment by tzarebczan** [comment]
Thanks for opening the issue! Do you know how this normally works for flatpak apps? Maybe @kcseb can take a closer look?

**Comment by REIS0** [comment]
sorry i really don't know, i'm using other flatpaks, discord and slack for example, and i've never seen this happening

**Comment by REIS0** [comment]
just to add that i've used to .deb version before and so far this doesn't happen

**Comment by kcseb** [comment]
Will take a look at this in a short bit. Will try it out on both a fresh install, and existing install.

**Comment by kcseb** [comment]
Can confirm that this indeed happens. When you run the Flatpak version via command-line, then spawn another instance, that secondary instance does not check to see if any others exist. 

However, a warning _is_ thrown from lbrynet ittself;
"SDK already running
Server already listening at localhost:5278. This is probably another LBRY app running. If not, games in the app will not work."

You mention being on PopOS? @REIS0 - Correct me if I am wrong, but that distribution is based on Debian? Or at the very least makes use of aptitude?

I'd highly suggest running the .deb as you were before rather than Flatpak. 

-----------------------------

I don't really know if Flatpak checks for existing spawns of any given application. That might be a question for the Flatpak folks themselves. I can tell you that this doesn't happen on the AUR version, either... So it seems to be attributed solely to the Flatpak version.

**Comment by REIS0** [comment]
@kcseb Is based on ubuntu, so i'll use the .deb version then

what is strange is that lbry is the only program that this happens actually, never saw something like that with other flatpaks

**Comment by kcseb** [comment]
I think it's a one-off issue with this package specifically. I'll look into adding a check for existing processes on startup. 

For now, if you could, post an issue on the Flathub repository. Thank you! 

https://github.com/flathub/io.lbry.lbry-app
https://github.com/flathub/io.lbry.lbry-app/issues

**Comment by REIS0** [comment]
done

**Comment by tzarebczan** [comment]
Closing this for now since it's documented on the flathub issue.
