### ISSUE TITLE
restore sidebar ads following testing period

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#4012]
We disabled sidebar ads to test if it scared people away. Re enable them following  the test.

**Comment by Tcll** [comment]
this could possibly be why I can't start LBRY without a VPN, including on older versions... smh

shame on you for using malicious domains like google and aws
and for using viruses (ads)

**Comment by kauffj** [comment]
@Tcll ads were never included in the desktop app

**Comment by Tcll** [comment]
@kauffj honestly, I was kinda referring to both in that statement
but yes the client absolutely uses aws, which is likely why I have that error without a VPN.
(I haven't created an issue on it because I don't feel a need to, the mention of ads combined with aws is why I'm posting here)

but with that said, there are better FOSS alternatives to analytics and advertising that aren't based around malicious platforms like Google and Amazon.
I can't name any off hand as I've only heard others talk about them...
I'm not particularly interested myself as I believe in support over revenue
(I give my support where due/possible on the platform, so ads/analytics are a kick to the balls for me)
