### ISSUE TITLE
Variable for string 942 causes mixed language sentence

### ISSUE THREAD

**Issue by infinite-persistence-2016** [lbryio/lbry-desktop#4124]
**String:** `942 Official YouTube Creator - Last updated %time_ago%`
**Problem:**:  The replaced text is in English, so we end of up mixed languages.
**Example:**:  "Kreator YouTube Rasmi - kemaskini terakhir pada **a week ago**"

I think this is because the string from `relativeDate()` is not localized.

**Comment by tzarebczan** [comment]
Thanks for filing this issue @infinite-persistence ! Yea, that must be it. This also happens in other places we use relative dates. Want to help us look for a solution?

**Comment by tzarebczan** [comment]
Actually, we do have it working in some places, but not on the homepage where I first checked.  
![image](https://user-images.githubusercontent.com/8120721/81129115-51559280-8f11-11ea-8f55-222d54b36b2a.png)

**Comment by infinite-persistence** [comment]
Ok, I'll give this a shot. (I switched accounts due to key and various problems, abonding that account).

There are currently 2 ways of getting relative time:  the one mentioned above, and `DateTime`. They are not in sync:
![mismatch](https://user-images.githubusercontent.com/64950861/81442413-25067400-91a6-11ea-8114-8d80c98c19ae.png)

(1) I'll try to sync the implementation of these 2 functions, unless told otherwise.
(2) Are there any rules on editing or removing existing string entries in `app-string.json`?

**Comment by infinite-persistence** [comment]
Looking further, I think I'll:
1. Leave `relativeDate` untouched.
2. Switch all usages of `relativeDate` in `lbry-desktop` to `DateTime`.  I think this one is more correct, and was recently adjusted to match YouTube.
