### ISSUE TITLE
Limit description contents to ~6K chars

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4369]
If you create a description that's too long, the publish will fail with a claim script too large error. We can either handle that and tell the user it's too long, or impose a limit. A user mentioned 7K works, but it will vary on other areas like tags/title/name

**Comment by infinite-persistence** [comment]
I've managed to add character limits to `SimpleMDE`. I decided to go with 5000 since it's a nice number and YT uses 5000 as well.

However, while testing, I found this:
✔️ 5000 English characters -- ok.
❌ 5000 Japanese characters -- same tx error.
I think it's because CJKs are multi-byte.  You've also hinted that there are other factors as well.

Do you think it's still worth submitting the PR when there are so many factors for failure?

**Comment by infinite-persistence** [comment]
Hm ... I'll submit it anyway, since it indirectly fixes another existing issue (see PR).
