### ISSUE TITLE
Making lbry.tv GDPR compliant

### ISSUE THREAD

**Issue by finer9** [lbryio/lbry-desktop#4713]
Our advertising partner requires that we become gdpr compliant on lbry.tv by Sept 30.

While there are several facets of compliance, a main and obvious one is the 'cookie warning banner' you see on many sites today.

https://www.cookieyes.com/gdpr-cookie-consent-banner-examples/

An 'informational' type is a good start for us.  It should run along the bottom of the screen and disappear when agreed-to.

**Comment by kauffj** [comment]
lbry.tv uses cookies and the GDPR is dumb [Agreed]

**Comment by seanyesmunt** [comment]
Do we just need to change the text on the banner that is already being used? Or are larger changes required?

<img width="1248" alt="Screen Shot 2020-08-27 at 2 54 57 PM" src="https://user-images.githubusercontent.com/16882830/91483204-50a48b80-e875-11ea-8dbf-9fd000cb66d3.png">

**Comment by finer9** [comment]
I think this banner is a perfect place.  We just need to use the version of
the text that says they are agreeing to the cookies, not the option of
rejecting them.

**Comment by kauffj** [comment]
Does this still need to be done? What is this holding back, if anything?

**Comment by 9mido** [comment]
I suggest creating something like https://www.youtube-nocookie.com/embed/ but for embedded odysee videos. As a business owner, I wouldn't embed odysee videos unless there is a way to embed them without cookies.

As for the cookie banner at the bottom of the page you can buy something like OneTrust CookiePro or Cookiebot. It is not enough to just display a banner and click something to dismiss the banner. You need to be able to have your users control which cookies they are willing to accept/decline. Parts of the website will not work unless cookies are accepted. 

See this as an example of what you should create:

https://stripe.com/cookie-settings

Something needs to be done about cookies otherwise you will have some big legal fines to pay.
