### ISSUE TITLE
push translation strings

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#5291]

**Comment by infinite-persistence** [comment]
In the Discord `translators` channel, we are wondering:
- since Web/Odysee changes are tied to `master`, can the Push be scripted and executed daily (or perhaps weekly for some debouncing) so that Web/Odysee strings won't be in limbo for months while waiting for the next Push?

If accepted, I'm guessing we'll probably need to split or freeze the translation set for each Desktop release, so that any string removal that happen later won't affect it.

**Comment by kauffj** [comment]
Because updating them requires a private key, it's our CI system that needs to be updated to perform this task.

**Comment by kauffj** [comment]
Looking at doing this on merge to master as part of GitHub actions

**Comment by seanyesmunt** [comment]
I just pushed new strings. I hope to add them to our CI setup sometime soon

**Comment by kauffj** [comment]
@infinite-persistence until this is scripted please ping here if they're out of date

**Comment by infinite-persistence** [comment]
Friendly reminder:
- `Last update`: ~1 month
- `Delta`: ~60+ new strings
