### ISSUE TITLE
Double play of videos/sound for in-app and for fullscreen

### ISSUE THREAD

**Issue by marzoul** [lbryio/lbry-desktop#5311]
**Bug**
When launching a video, the sound is played twice simultaneously, resulting in weird sound quality.
Muting sound only mutes "one" of the instances being played, resulting in good sound quality.
Pausing video has similar issue.

**To Reproduce**
1. Launch any video from library
2. Listen to sound, it is being played twice with slight delay
3. Move forward in the video with right arrow
4. Listen to sound, one track has advanced forward in time, while the other continues to play unaffected
5. Click on mute button
6. Listen to sound, it is still being played, but only once this time
7. Hit F for fullscreen
8. Click on mute button
9. Listen to sound : this time it is all muted

**Expected behavior**
Only one sound track should be played.

**System Configuration**
Archlinux with AUR package built from source (package page : https://aur.archlinux.org/packages/lbry-desktop-git/)
Tested with commit ee0bdf3a823961260e4ed5bfc3e77c8ec34845c2 from 2021-01-14
Has been happening from some time, unknown (only recompiled recently)

**Comment by tzarebczan** [comment]
Thanks for filing the issue. From Library, you mean from the Library section in the side bar of content that's already downloaded? 

Does it happen on the release AUR also? What about the appimage at lbry.com/get? 

I'm not seeing that here on Windows, will have to try the aur sometime.

**Comment by marzoul** [comment]
It does not happen with the release binary package https://aur.archlinux.org/packages/lbry-app-bin/
Advertised version is 0.49.3
I see that it is built from .deb package from there : https://github.com/lbryio/lbry-desktop/releases/download/v0.49.3/LBRY_0.49.3.deb
I don't know about the appimage and not tried.

**Comment by marzoul** [comment]
Yes, I meant the Library section in the side bar of content that's already downloaded.

**Comment by infinite-persistence** [comment]
I believe this, #5328 [videos play in background after floating player closed](https://github.com/lbryio/lbry-desktop/issues/5328),  and my reportings in Discord are the same thing.

Today, it's also happening on lbry.tv and `dev:web`. 

I'm guessing it's due to the new `fetch` not being disposed when there is a re-render. I'm seeing interleaved fetches causing an additional `<video>` to be created.  

- When things are working (which clearing the cache usually makes it work), the fetch-and-response is usually immediate:
    - ![image](https://user-images.githubusercontent.com/64950861/105156703-249ce600-5b47-11eb-96b6-f17948810f93.png)

- But sometimes, things go wrong (I'm not sure if the error is relevant or not since the issue sometimes appear without this error):
    - ![image](https://user-images.githubusercontent.com/64950861/105156739-33839880-5b47-11eb-9685-9f632bc065bc.png)

- Anyway, after that, and perhaps with some other unknown sequence, I'm starting to see interleaved fetches and double creation of `<video>` without a `dispose`:
    - ![image](https://user-images.githubusercontent.com/64950861/105157043-8bba9a80-5b47-11eb-8b5d-c1dd0a13beec.png)

**Comment by tzarebczan** [comment]
This should be fixed now in all packages/on master.
