### ISSUE TITLE
Token purchase - country German Democratic Republic included

### ISSUE THREAD

**Issue by fte378** [lbryio/lbry-desktop#5397]
**Bug**
During buying new tokens through the desktop app a country selection list is presented which includes "German Democratic Republic". The state doesn't exist anymore for over 30 years, so this entry should be removed.

**To Reproduce**
1. Go to wallet
2. Click on 'Buy'
3. Click on 'Select country'
4. See 'German Democratic Republic' in the list

**Expected behavior**
For Germany only Germany should be included.

**System Configuration**

Desktop app Version 0.49.4 (0.49.4)

{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "lbrynet_version": "0.88.0",
    "os_release": "20.2.0",
    "os_system": "Darwin",
    "platform": "Darwin-20.2.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "3.7.4",
    "version": "0.88.0"
  }
}

**Comment by tzarebczan** [comment]
We're using a package that's has a bunch of country names, but also some outdated ones. Thanks for the issue.

**Comment by kauffj** [comment]
This has come up before, we really should fix this. It can't be that hard.

**Comment by DispatchCommit** [comment]
The package we use hasn't been updated in 4 years, and looking at networks forks of the repo doesn't reveal any active forks.

Some possible replacements packages: 
- https://www.npmjs.com/package/countries-list (this looks the best)
- https://github.com/andyburke/countrydata
- https://www.npmjs.com/package/country-data-list
- https://www.npmjs.com/package/i18n-iso-countries


Raw JSON data for Countries (in case someone wants to fork and update country-data themselves):
- https://github.com/annexare/Countries/tree/master/data
- https://github.com/samayo/country-json
- https://github.com/umpirsky/country-list
- https://gist.github.com/incredimike/1469814


Feedback / recommendations  / reviews welcome for any of the listed libraries. Feel free to suggest a replacement library if you know of a package that is maintained better(or just, maintained _at all_), with similar functionality. 

----

The current list is actually fairly inaccurate in regards to countries that still exist, but it's probably better to have *too many* countries in the last, rather than too few in the time being.

![image](https://user-images.githubusercontent.com/45262335/106095777-37845d00-60e9-11eb-858b-6e485ce64535.png)

**Comment by xdevs23** [comment]
![image](https://user-images.githubusercontent.com/6959245/112764977-38fbd400-900b-11eb-825a-2bb9eae8dc92.png)

It says status: deleted so maybe just filter that out?
