### ISSUE TITLE
confirmation on comment deletion

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5416]
![image](https://user-images.githubusercontent.com/8120721/106063990-17dc3d00-60c7-11eb-8fb4-6f95679fe4b1.png)

**Comment by DispatchCommit** [comment]
Side effect caused by https://github.com/lbryio/lbry-desktop/pull/5381

I didn't realize the menus behaved in this maner. The menu buttons will trigger `onMouseUp` so it's possible to click a menu item while it's animating in (dropping down).

This is actually an issue in all locations where dropdowns appear.

This looks like (another) bug in the dependency reach-ui sadly: https://github.com/reach/reach-ui/issues/563

I would expect the button triggering the menu animation to consume the click event, yet it doesn't.

**Comment by DispatchCommit** [comment]
Looking into reach-ui's source code, reach-ui will trigger tthe `onSelect` callback (which is our button "click") on `mouseUp` without checking if the click originated on the same element. This causes weird behavior. 

https://github.com/reach/reach-ui/blob/c5234721d372e2ab2a7745475007605e78d18895/packages/menu-button/src/index.tsx#L451-L472

**Comment by DispatchCommit** [comment]
Reach-UI exposes it's internal event handlers for us to hook into if need, so using those handlers we can actually add some additional logic to the handlers to prevent the click event from triggering earlier than the animation finishes.

This is what I came up with: add an event handler on the root activation button that toggles a boolean state variable true / false. Upon clicking the menu activation button, set this variable to false to indicate we should not pass click events through. Then set a timeout function for the same length as the drop-in animation. 

Now on the menu items that drop in, we need to override the underlaying component's `onMouseUp` function in order to prevent the event from firing, and thus stopping us from triggering the `onSelect` function of this component. 

But we only want to prevent this event from firing while our animation is active, so check the state variable we set previously, and if it is `false`, stop the event form firing with `preventDefault`. If it is true, allow the event to fire as usual.

Disabling the moueUp event, disables the onSelect event, and thus fixes the issue with accidental clicks. Here's the code:

```js
            <div className="comment__menu">
              <Menu>
                <MenuButton onMouseDown={() => {
                  setMouseClickCompleted(false);
                  setTimeout(() => setMouseClickCompleted(true), 200)
                }}>
                  <Icon
                    size={18}
                    className={mouseIsHovering ? 'comment__menu-icon--hovering' : 'comment__menu-icon'}
                    icon={ICONS.MORE_VERTICAL}
                  />
                </MenuButton>
                <MenuList className="menu__list--comments">
                  {commentIsMine ? (
                    <>
                      <MenuItem
                        className="comment__menu-option menu__link"
                        onMouseUp={e => !mouseClickCompleted && e.preventDefault()}
                        onSelect={handleEditComment}
                      >
                        <Icon aria-hidden icon={ICONS.EDIT} />
                        {__('Edit')}
                      </MenuItem>
                      <MenuItem
                        className="comment__menu-option menu__link"
                        onMouseUp={e => !mouseClickCompleted && e.preventDefault()}
                        onSelect={handleDeleteComment}
                      >
                        <Icon aria-hidden icon={ICONS.DELETE} />
                        {__('Delete')}
                      </MenuItem>
                    </>
```

Not the cleanest looking, but reach-UI has weird opiniated behavior that causes issues. 

From reach-ui's docs: https://reach.tech/menu-button/#Events

> You may want to pass your own click handler to a MenuButton, MenuItem or MenuLink that, in some cases, intercepts and prevents the default behavior from ocurring.
> This won't work because we actually do not call the onClick handler to activate Menu or select MenuItem or MenuLink components.
> This is because a user may mouse down on a menu button, drag over a menu item and then select it by releasing the mouse trigger.
> A user may also start clicking one item, then drag to another item before mouseup to change their selectiion.

I disagree with this user intention flow, if a `mouseDown` and `mouseUp` do not start and end on the same component, then no `onClick` event should fire, as that is standard behavior across applications, sites, and other UI's.

----

Now that I've realized how reach-ui works, I believe there are other bugs and issues logged due to it's behavior causing issues (such as being unable to open a link in a new tab, the `home` / `end` keys not working in the search bar, and this click side effect.

**Comment by DispatchCommit** [comment]
relevant lines modified from here in source: 
https://github.com/lbryio/lbry-desktop/blob/8c21ec30e82c98a704594b1314a981530dfbaa4c/ui/component/comment/view.jsx#L239-L258

**Comment by DispatchCommit** [comment]
There's likely a better way to implement this dropdown in CSS now knowing this flaw / limitation in reach-ui.

Instead of applying the translation to the parent popover component, we instead do `overflow: hidden` on the component, and translate it's child component up by 100%, resulting in this animation:

![better-dropdown](https://user-images.githubusercontent.com/45262335/106107692-15480a80-60fc-11eb-90ea-354153879a9c.gif)

By causing the child to be clipped by the translation within the parent component, the component shouldn't be able to register the mouseUp event during the animation phase.

#5381 Should probably be reverted knowing this behavior exists, and I'll PR a replacement animation that behaves better with the reach-ui event handling. We could still add a deletion confirmation message when deleting a comment, but it shouldn't be so easy to accidentally click delete in the first place.

**Comment by tzarebczan** [comment]
This was fixed as we reverted the code.
