### ISSUE TITLE
wallet server status shows not connected even though it's successfully connected

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5529]
If you add a wallet server under Setitngs >advanced in the desktop app, it will say it's not connected even though it is. Maybe the API on the SDK changed on how it shows connected servers recently. 

sample: spv20.lbry.com, 50001 or spv18.lbry.com, 50001

**Comment by Ruk33** [comment]
Just as documentation, if for some reason you end up with an invalid wallet address, the app won't load. In order to fix it, you need to change the file `\AppData\Local\lbry\lbrynet\daemon_settings.yml` and remove `lbryum_servers`. Restart the computer and should be fine.

@tzarebczan the issue is that the frontend is trying to check if it's connected using the domain, but the server is using it's ip. This means, `spv20.lbry.com` gets returned from the server as `51.81.47.19` (its ip) and thus, the frontend can't perform the check.

```js
              serverConfig.map((entry, index) => {
                const [host, port] = entry;
                const available = activeWalletServers.some(
                  s => s.host === entry[0] && String(s.port) === entry[1] && s.availability
                );
```

from `lbry-desktop\ui\component\settingWalletServer\view.jsx`

@tzarebczan do you have any possible solution/thoughts for this?

**Comment by Ruk33** [comment]
Hello @tzarebczan , do you think maybe we can display host IPs instead of domains? If not, maybe we can change the server code a bit to also store the host sent by the client as an alias. Thoughts?

**Comment by Ruk33** [comment]
Hello @tzarebczan , do you have any feedback for this one? Regards.

**Comment by tzarebczan** [comment]
yep, we'll need to fix that one on the SDK...I was thinking we could just check that it's connected or not, but we support multiple servers so that won't work. Disregard for now, but thank you for looking into it!

**Comment by Ruk33** [comment]
Sure thing @tzarebczan . Thanks 👍

**Comment by tzarebczan** [comment]
https://github.com/lbryio/lbry-sdk/issues/3209 - requires this fix. Also rename his to "hub" wherever it says wallet server.

**Comment by Ruk33** [comment]
The issue is no longer happening since backend is now sending the proper host and thus, the following check can be performed correctly:

![image](https://user-images.githubusercontent.com/1719111/128412031-d0b8abb2-4208-438c-8bfc-3bfb7ad1564c.png)

![image](https://user-images.githubusercontent.com/1719111/128411929-16723ef0-ff0e-4dcd-b53e-e15b64a7567a.png)

**Comment by tzarebczan** [comment]
Ah great, thanks for confirming!
