### ISSUE TITLE
restore subtitles/CC button when transcoder fix is in

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6233]
![image](https://user-images.githubusercontent.com/8120721/121912882-ee7f1f00-ccfe-11eb-86ca-603a9ddc0a7c.png)

This is on https://odysee.com/@OdyseeCafe:5/ODYSEE-LIVESTREAM-01:c

**Comment by DispatchCommit** [comment]
This is the expected behavior given the metadata we receive from the playlist file of transcoded files. The player team will need to correct the m3u8 files and add appropriate metadata to properly fix this.

https://developer.apple.com/library/archive/qa/qa1801/_index.html
> iOS 7 now supports the TYPE attribute of the EXT-X-MEDIA tag having a value of CLOSED-CAPTIONS. This allows for explicit declaration of closed caption content in the playlist file. See the HTTP Live Streaming Draft Protocol Specification for the details.
iOS 7 also supports a CLOSED-CAPTIONS attribute for the EXT-X-STREAM-INF tag. You can declare the absence of closed caption content in the playlist by specifying CLOSED-CAPTIONS=NONE on the EXT-X-STREAM-INF tag. The "Unknown CC" option as shown in Figure 1 will not be displayed in the selection when the absence of closed caption content is declared.
Also, if the media does not contain alternate audio or subtitles, and the absence of closed caption content is declared, the alternate track button will not be displayed.

**Comment by jessopb** [comment]
Restore button when above transcoder issue is closed.
