### ISSUE TITLE
%E2%80%8B or other characters appended on https urls crashes the app

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#6243]
Some pages have odysee links with 
`%E2%80%8B` appended.
https%3A%2F%2Fodysee.com%2F%40Franssen%3A3%E2%80%8B
This crashes the app.
I believe lbry-redux trying to use the i18n `__` function is failing.
1) strip %E2%80%8B
2) fix redux trying to use non-existent i18n function on errors

**Comment by marko-lorentz** [comment]
@sanabhass and me had a short look at the behaviour (not the code) and it seems as if the crash occurs for any URL that does not end with `:<hexnumber>`:
 
* https://odysee.com/@lusty:d/diablo-2-resurected-promesse-non-tenue:6 works fine
* https://odysee.com/@lusty:d/diablo-2-resurected-promesse-non-tenue:6x will break
* https://odysee.com/@lusty:d/diablo-2-resurected-promesse-non-tenue:6nice will break

The same happens when you break the format in the @-part of the URL which apparently needs `@<channel>:<hexnumber>`:
* https://odysee.com/@lusty:dk/diablo-2-resurected-promesse-non-tenue:6 will break

Conclusion based on Occam's razor: There is a custom parsing somewhere that assumes URLs to be exactly like `/@<channel>:<hexnumber>/<claim-title>:<hex number>`. This code is not properly secured by checks.

**Comment by tzarebczan** [comment]
Issue moved to [OdyseeTeam/odysee-frontend #202](https://github.com/OdyseeTeam/odysee-frontend/issues/202) via [**ZenHub**](https://www.zenhub.com/)
