### ISSUE TITLE
comment reaction list loops with 1 channel

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6561]
If a user has 1 channel, the reaction list call for comments will loop.

**Comment by infinite-persistence** [comment]
Seems pretty stable now.
- Since we buffer up the IDs and fetch in larger batches, it won't be 1:1 with `comment.List` like before (should be fewer calls when scrolling fast).
- Can't explain the spike at `1:00 - 1:30` though.  The only "extra fetch" that I know is when we switch active channels, but that should just be 1 call to catch up on all comment IDs.

![image](https://user-images.githubusercontent.com/64950861/126591948-6379c5da-5e99-4e6f-8b7c-d026f1a9af03.png)
