### ISSUE TITLE
Newly-uploaded thumbnail doesn't resolve when ready

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6954]
In the Upload Page, upload a new thumbnail using the file uploader. The image has to be unique and not in the speech server yet.

The uploaded image will never appear due to an error. Not sure due to webp, speech, CDN, or just the timeout being too short.
- <img src="https://user-images.githubusercontent.com/64950861/130745186-cf2126bd-b8c5-44ce-b577-d748a86f6100.png" width="400">
- <img src="https://user-images.githubusercontent.com/64950861/130745088-c46b4fa7-4c68-4687-b39b-89afa70cba14.png" width="400">
- error: "could not resolve stream URI"

**Comment by tzarebczan** [comment]
This is a limitation of thumbnail uploads via LBRY because they require confirmation before being resolvable and readable by the video player. That's why we added that placeholder that says "this will update later" .

It would be nice to update the image in place https://github.com/lbryio/lbry-desktop/issues/5334
