### ISSUE TITLE
Comment direct link shows "Show Reply" when there are none

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#7146]
https://odysee.com/@thomas.zarebczan:c?view=discussion&lc=b2918a0de3c943b14c02a0a959bda11892e2d6a0c24ee777f2586972d3ec05ac

![image](https://user-images.githubusercontent.com/8120721/134229765-c490d2f9-abe0-4275-8bbe-df43574b3d5f.png)

**Comment by infinite-persistence** [comment]
Vlad's intervention made it not reproducible (commentron data matches UI).

If it happens again, we'll need to grab `comment.List` for the top level and the "Show reply".  

Most likely not due to blocked channels, as I've seen in Discord saying that 2 people are communicating at top-level, but can't see each other at the reply level.

**Comment by tzarebczan** [comment]
I can try again, but the comment list showed 0 items for those replies. If I loaded without the comment id in URL, it didn't show the reply button.

**Comment by tzarebczan** [comment]
Deleted those 2 messages, so it should be reproducible again.

**Comment by infinite-persistence** [comment]
Hm, looks correct now (no `replies` field, no "Show replies").  Maybe commentron blocklist sync'd up since then.

![Screenshot from 2021-09-23 09-00-18](https://user-images.githubusercontent.com/64950861/134440917-07724e07-7191-43c4-b27a-8b70c79339cd.png)

Anyway, will try to add back the "comment(s) blocked" message to narrow it down.

**Comment by tzarebczan** [comment]
Blah, was a strange one, I'll try to repro on another claim. If it were blocked, I'd still see the comments on commentron, but there were the only 2.

**Comment by infinite-persistence** [comment]
One scenario to reproduce this:  mute all channels in the reply -- this is filtered app-side and commentron doesn't know.

But I don't think this is the case here
