### ISSUE TITLE
Write out proposed sync re-design

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#7392]

**Comment by jessopb** [comment]
### Introduction

In a normal app, we could sync app settings with a server merging them as necessary and send a single request to push any new data.

With LBRY sdk / sync, sync is fetched as an encrypted bundle, and applied to app preferences. Changes to remote sync data is done by pushing the entire encrypted bundle. We can check only that the remote hash is the same.

### Language in the App
Talking about the sync server, I’ll use `sync set` and `sync get`. 
Talking about sync facilities in the sdk, there is just `sync hash` and `sync apply`. `sync apply` applies new data to the wallet, or without data, just fetches the current data.
Some of the client settings are stored in SDK Preferences using SDK methods `preference set` and `preference get`. After `preference get`, preferences must be populated into settings. `‘doGetAndPopulatePreferences()’` is the function that generally handles that.

### The Problem

Clicking follow multiple times or changing a setting rapidly can cause confusing, inconsistent behavior because of the number of round trips necessary to make sure each change is being applied to the most current remove version. This can be a problem between devices or even between tabs.

The docs for the new sync system explicitly states that it is not a source of truth. So for multiple apps / tabs / devices to maintain integrity, if sync is enabled, we must ensure that we have the most up to date remote version before applying changes on top of it and pushing a new version.

### The Solutions So Far
Up until now we’ve been adding more and more checks in the app to make sure we have the current sync version: Timer intervals, delays, pull on focus, pull when entering the settings page and sync on save, etc. This can still fail.

KP has some additions to this system including aborting sync actions if there are newer ones initiated, tracking online/offline status, etc. 
https://github.com/OdyseeTeam/odysee-frontend/pull/520/files


### My Proposal
It would be good to never expect the app to have the latest sync. Yes, run the websocket listener, but, after changing a setting or adding or removing a follow, remember a list of those atomic actions while fetching the most up to date sync version, applying the list, and pushing the new sync.

This can be done two ways:
1) Remember a list of changes to push up from SDK preferences to `sync set`, but apply the setting immediately.
2) Remember a list of changes and integrate the temporary changes into the selectors for settings, subs, tags. Delete the list after `sync set`. This was my first idea, but I don’t think I need to flesh it out - it is inferior.

We’ll add prefBatch and prefBatchApplying to redux settings store (or sync?).
```
prefBatch : { 
subscriptionsAdded: [ @example ], 
settingsChanged: { autoplay: true }, }
prefBatchApplying : {}
```

Follow @example
- @example is added to Subscriptions, dispatches action named CHANNEL_SUBSCRIBE marked for preference sync.
- Immediately update app subscriptions in redux store
- Add to `prefBatch` in redux store (as above)
- If `prefBatchApplying` is empty:
  - ‘sync get’ and ‘sync apply’ sync to wallet (updating wallet preferences)
  - doGetAndPopulate gets prefs, moves `prefBatch` (if not empty - otherwise bails) to `prefBatchApplying`, and populates to 
  - app settings. (it’s at this point that further clicks could be erased by this function)
  - if at this point another preference is triggered, we add it to `prefBatch`
  - preference_set `prefBatchApplying` items to preferences
  - Take sync_apply data and lbryio.call(‘sync’ ‘set’) it.
  - If it fails - what to do? (You have a follow in local state that isn't in sync) We can move items back into prefBatch and keep trying?
  - Delete `prefBatchApplying` if ‘sync set’ is successful.
- if `prefBatch` is not empty:
  - Run syncloop again

### Sanity questions:
Can we get rid of the save / back button?
Are there settings when we should facilitate a delayed system that requires saving the settings before they take effect?
Make sure we cover sync / no sync / transition cases in app?
Still worthwhile to run the websocket or at least interval polling (or whichever)? (I think so).
