### ISSUE TITLE
Fix desktop thumbs

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#7536]
When viewing publishes, for example, browser is clearing viewing a thumb download as an image, yet it's not showing up in the ui.

**Comment by Ruk33** [comment]
@jessopb seems like thumbnails are empty from the service:
![image](https://user-images.githubusercontent.com/1719111/162981566-15a48a0f-1908-446b-9365-34b62b464c1b.png)

**Comment by jessopb** [comment]
We should at least make sure the placeholder image shows.

**Comment by Ruk33** [comment]
@jessopb the default image is being displayed. It got fixed in this PR https://github.com/lbryio/lbry-desktop/pull/7541 by passing the `uri` parameter.

![image](https://user-images.githubusercontent.com/1719111/164783922-3f50a97c-98f7-44e5-9d72-59884f9ada6f.png)

Please let me know if you need anything else from my end.
