### ISSUE TITLE
support for Jack Audio Driver in Linux.

### ISSUE THREAD

**Issue by juanpc2018** [lbryio/lbry-desktop#7591]
Like VLC Player or Xine...
has support for Jackd2 Audio Driver...

https://github.com/jackaudio/jack2-releases/releases
https://jackaudio.org/downloads/

**Comment by belikor** [comment]
If you are talking about the LBRY Desktop application, this is an Electron application. Electron applications are basically a stripped down Chromium browser, with some Javascript-ReactJS-CSS code for the interface. Basically, it's an application running inside a browser.

As far as I understand VLC, Xine, mpv, and other video applications are native applications running directly on the Linux libraries, so they can implement interaction with the `jackd` daemon.

Therefore, it seems to me that in order to do what you want, the entire Electron platform (a web browser) should support `jackd`. Maybe if this is done in the Electron project, all applications based on Electron would be able to use `jackd`.

**Comment by juanpc2018** [comment]
The only Browser that supports Jackd is Firefox...
and Not by default...
Needs to be compiled with the option..

https://www.zamaudio.com/?p=1580

https://askubuntu.com/questions/923990/jack-pulseaudio-and-firefox-enable-jack-for-firefox-in-the-near-future

https://github.com/KXStudio/Repository/issues/117

**Comment by EinoHR** [comment]
+1 for belikor, I'm afraid this is an Electron feature request...

**Comment by jessopb** [comment]
Maybe reopen when electron does it.
